/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as CalculadoraRouteImport } from './routes/calculadora'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as FulfillmentRouteImport } from './routes/fulfillment'
import { Route as PromocoesRouteImport } from './routes/promocoes'
import { Route as RecuperacaoRouteImport } from './routes/recuperacao'
import { Route as VendasRouteImport } from './routes/vendas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadoraRoute = CalculadoraRouteImport.update({
  id: '/calculadora',
  path: '/calculadora',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const FulfillmentRoute = FulfillmentRouteImport.update({
  id: '/fulfillment',
  path: '/fulfillment',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocoesRoute = PromocoesRouteImport.update({
  id: '/promocoes',
  path: '/promocoes',
  getParentRoute: () => rootRouteImport,
} as any)
const RecuperacaoRoute = RecuperacaoRouteImport.update({
  id: '/recuperacao',
  path: '/recuperacao',
  getParentRoute: () => rootRouteImport,
} as any)
const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/produtos': typeof ProdutosRoute
  '/calculadora': typeof CalculadoraRoute
  '/estoque': typeof EstoqueRoute
  '/fulfillment': typeof FulfillmentRoute
  '/promocoes': typeof PromocoesRoute
  '/recuperacao': typeof RecuperacaoRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/produtos': typeof ProdutosRoute
  '/calculadora': typeof CalculadoraRoute
  '/estoque': typeof EstoqueRoute
  '/fulfillment': typeof FulfillmentRoute
  '/promocoes': typeof PromocoesRoute
  '/recuperacao': typeof RecuperacaoRoute
  '/vendas': typeof VendasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/produtos': typeof ProdutosRoute
  '/calculadora': typeof CalculadoraRoute
  '/estoque': typeof EstoqueRoute
  '/fulfillment': typeof FulfillmentRoute
  '/promocoes': typeof PromocoesRoute
  '/recuperacao': typeof RecuperacaoRoute
  '/vendas': typeof VendasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/produtos'
    | '/calculadora'
    | '/estoque'
    | '/fulfillment'
    | '/promocoes'
    | '/recuperacao'
    | '/vendas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/produtos'
    | '/calculadora'
    | '/estoque'
    | '/fulfillment'
    | '/promocoes'
    | '/recuperacao'
    | '/vendas'
  id:
    | '__root__'
    | '/'
    | '/produtos'
    | '/calculadora'
    | '/estoque'
    | '/fulfillment'
    | '/promocoes'
    | '/recuperacao'
    | '/vendas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProdutosRoute: typeof ProdutosRoute
  CalculadoraRoute: typeof CalculadoraRoute
  EstoqueRoute: typeof EstoqueRoute
  FulfillmentRoute: typeof FulfillmentRoute
  PromocoesRoute: typeof PromocoesRoute
  RecuperacaoRoute: typeof RecuperacaoRoute
  VendasRoute: typeof VendasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadora': {
      id: '/calculadora'
      path: '/calculadora'
      fullPath: '/calculadora'
      preLoaderRoute: typeof CalculadoraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fulfillment': {
      id: '/fulfillment'
      path: '/fulfillment'
      fullPath: '/fulfillment'
      preLoaderRoute: typeof FulfillmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promocoes': {
      id: '/promocoes'
      path: '/promocoes'
      fullPath: '/promocoes'
      preLoaderRoute: typeof PromocoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recuperacao': {
      id: '/recuperacao'
      path: '/recuperacao'
      fullPath: '/recuperacao'
      preLoaderRoute: typeof RecuperacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProdutosRoute: ProdutosRoute,
  CalculadoraRoute: CalculadoraRoute,
  EstoqueRoute: EstoqueRoute,
  FulfillmentRoute: FulfillmentRoute,
  PromocoesRoute: PromocoesRoute,
  RecuperacaoRoute: RecuperacaoRoute,
  VendasRoute: VendasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
